### ISSUE TITLE
Clean up generated contents in AWS after a 5 days

### ISSUE THREAD

**Issue by dave-tucker** [instructlab/instructlab-bot#34] opened 2024-03-17 11:25 UTC
This should be simple enough to do with [Expiry[(https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-expire-general-considerations.html).
We can set the Expiry when we upload objects and will be taken care of for us.

**Comment by vishnoianil** [comment] 2024-04-26 07:09
Duplicate of #304 , lets track it through that.

**Closed by vishnoianil** 2024-04-26 07:09 UTC
Labels: enhancement, gobot
